### ISSUE TITLE
Fix language copy (URL)

### ISSUE THREAD

**Issue by thomasduenser** [sulu/SuluArticleBundle#270]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | 0.5.1
| Sulu Version | 1.5.3

#### Actual Behavior

When copying the content of an article from a locale `de` to another locale `en`, it's not possible to change the URL for `en` as no entry in `ro_routes` table is available after copying.

#### Expected Behavior

It should be possible to change the URL for the copied locale.

#### Steps to Reproduce

1. Create an article in `de`
2. Copy the content from `de` to `en`
3. Try to change the URL for `en`

**Comment by wachterjohannes** [comment]
is already fixed in version 0.7.0

**Comment by Asgaros** [comment]
Hello @wachterjohannes 

Sorry for writing in this old ticket. You have mentioned in your last comment that this issue is already fixed since version 0.7.0, but a fix for this issue is listed first in the changelog for version 1.0.0-RC1 (2017-11-14). We faced a similar issue recently in a project which is unfortunately still using 0.7.0 - so I am curious if this problem was really sorted out in that version or instead got fixed in version 1.0.0-RC1 (2017-11-14). If your comment regarding the version was misleading, is it possible to provide a link to the commit in which this problem was fixed so I can apply this fix manually to our code base?
