### ISSUE TITLE
Questions : SuluArticleBundle does not install

### ISSUE THREAD

**Issue by lucas-gymex** [sulu/SuluArticleBundle#403]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 2.0.0

Hello,

I am finalizing a project using Sulu 2.0.0. I will need SuluArticleBundle, but when I do:
`composer require sulu/article-bundle`
an error occurs, I can not install it with my version of Sulu.
Is there a dev version that could be used or is it impossible?

Thank you in advance for your answers

**Comment by simonoche** [comment]
It's because you have to use 2.0.x version of this bundle, which is currently in alpha.

> composer require sulu/article-bundle 2.0.0-alpha3

**Comment by NeuralClone** [comment]
I've been attempting to install version 2.0.0 of this bundle and it still fails despite it apparently being out of alpha.

ocramius/proxy-manager requires PHP ^7.4.0 and ongr/elasticsearch-bundle requires PHP >=5.6,<7.4. Sulu 2.0.7 requires the former and sulu/article-bundle requires the latter. It creates a circular problem when attempting to install sulu/article-bundle.

If I try to use PHP 7.3, I get a fatal PHP error when Composer tries to update ocramius/proxy-manager. Understandable since it requires PHP 7.4. And when I switch back to PHP 7.4, `composer update` is unable to resolve an installable set of packages since ongr/elasticsearch-bundle requires PHP <7.4.

> Problem 1
    - ongr/elasticsearch-bundle v5.2.5 requires php >=5.6,<7.4 -> your PHP version (7.4.6) does not satisfy that requirement.
    - ongr/elasticsearch-bundle v5.2.4 requires php >=5.6,<7.4 -> your PHP version (7.4.6) does not satisfy that requirement.
    - ongr/elasticsearch-bundle v5.2.3 requires php >=5.6,<7.4 -> your PHP version (7.4.6) does not satisfy that requirement.
    - ongr/elasticsearch-bundle v5.2.2 requires php >=5.6,<7.3 -> your PHP version (7.4.6) does not satisfy that requirement.
    - Conclusion: don't install symfony/stopwatch v4.4.8
    - Conclusion: remove symfony/framework-bundle v4.4.8
    - Conclusion: don't install ongr/elasticsearch-bundle v5.2.6
    - Conclusion: don't install symfony/framework-bundle v4.4.8
...

There's a very long list of Symfony packages that generate several more conflicts since Symfony is locked at 4.4.8.

How can I resolve this conflict? I'm not entirely sure what I'm missing here. I'm not doing anything unusual and simply following the install instructions. This is with a fresh install of Sulu 2.0.7. Or is the sulu/article-bundle 2.0.0 tag not actually intended to be a stable release?

**Comment by nnatter** [comment]
Version 2.0 of the SuluArticleBundle was released about a month ago: https://sulu.io/blog/article-bundle-2-0-0-released

Therefore, this should not be a problem anymore.
