### ISSUE TITLE
RoutePath not saved with articles

### ISSUE THREAD

**Issue by speex404** [sulu/SuluArticleBundle#593]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | 2.3.1
| Sulu Version | 2.3.1, 2.3.2 
| PHP Version | 8.0.9
| Elasticsearch | 7.14.0
| DB Version | MySQL 8.0.23
| Browser Version | Chromium 92.0.4515

#### Actual Behavior
After reindexing the articles the frontend crashes for articles where no resourcelocator was set.

`Sulu\Bundle\ArticleBundle\Content\ArticleResourceItem::getRoutePath(): Return value must be of type string, null returned`

#### Expected Behavior

A reindex should not affect the resource locator.

#### Steps to Reproduce

- Add a new article in the Sulu backend:
  - Leave the URL field empty
  - Save the article

- Reindex the articles:
  - `bin/adminconsole sulu:article:reindex --drop --no-interaction`
  - `bin/websiteconsole sulu:article:reindex --drop --no-interaction`

- Open a page in the frontend where the `{{ routePath }}` is used.
  - The article has no routePath (HTTP 500)

#### Furthermore

The PHPCR node properties differ between the `live` and the `default` version.
Among other things there is no `routePath` property in the subset of the live session.

To reproduce this:
- Save an article without URL
- Copy its UUID
- Execute the following commands and compare the properties:
  - `bin/console  doctrine:phpcr:node:dump --identifiers "your articles UUID" --props --session default`
  - `bin/console  doctrine:phpcr:node:dump --identifiers "your articles UUID" --props --session live`
- There should be no `routePath` in the `live` version.

**Comment by niklasnatter** [comment]
Hey,
thanks for writing this up! 

Unfortunately I cannot find the time to investigate this at the moment. I hope to be able to have a look at it in the next two weeks 🙂

**Comment by niklasnatter** [comment]
I found some time to investigate this and create a PR to write the `routePath` to the correct session (https://github.com/sulu/sulu/pull/6210) 🙂 

For completion, this bug only happens when creating and publishing an article in the same step via the `Save and publish` toolbar action. It does not occur when publishing an existing article. Also, the bug disappears if the article is published a second time. The reason for this is that the `StructureSubscriber::mapContentToNode` method will set the property when the form contains a value for the route path.

**Comment by rogamoore** [comment]
Hey @nnatter, that's great news - thank you very much :)

**Comment by alexander-schranz** [comment]
https://github.com/sulu/sulu/pull/6210 is merged so this bug should be fixed with the patch release of sulu/sulu.
